[package]
name = "secompp22"
version = "0.1.0"
edition = "2021"
authors = ["Daniel Serezane <daniel.serezane@unesp.br>", "Gustavo Becelli <gustavo.becelli@unesp.br>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.0", features = ["postgres"] }
dotenvy = "0.15"
uuid = "1.2.1"